zipkin:
  image: openzipkin/zipkin
  ports:
    - "nginx-10-11-0-7:9411:9411/tcp"
  net: flannel

consul:
  image: consul
  ports:
    - "nginx-10-11-0-7:8400:8400/tcp"
    - "nginx-10-11-0-7:8500:8500/tcp"
    - "nginx-10-11-0-7:8600:8600/tcp"
  net: flannel

service-b:
  image:  spring-cloud-consul-example/service-b
  links:
    - "consul"
    - "hystrix-dashboard"
    - "zipkin"
  net: flannel

service-a:
  image:  spring-cloud-consul-example/service-a
  links:
    - "consul"
    - "service-b"
    - "hystrix-dashboard"
    - "zipkin"
  net: flannel

admin-dashboard:
  image:  spring-cloud-consul-example/admin-dashboard
  ports:
    - "nginx-10-11-0-7:8040:8040/tcp"
  links:
    - "service-a"
    - "service-b"
    - "zuul"
    - "hystrix-dashboard"
    - "consul"
  net: flannel

zuul:
  image:  spring-cloud-consul-example/zuul
  ports:
    - "nginx-10-11-0-7:8060:8060/tcp"
  links:
    - "consul"
    - "service-a"
    - "zipkin"
  net: flannel

hystrix-dashboard:
  image:  spring-cloud-consul-example/hystrix-dashboard
  ports:
    - "nginx-10-11-0-7:8050:8050/tcp"
  links:
    - "consul"
  net: flannel